#spring:
#  datasource:
#    username: root
#    password: root
#    url:jdbc:mysql://localhost:3306/productdb
#    driver-class-name: com.mysql.jdbc.Driver
#
#  Jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect

# YOU CAN USE APPLICATION.PROPERTIES OR APPLICATION.YML FILE EITHER ONE.